### ISSUE TITLE
How do I trasverse dictionary?

### ISSUE THREAD

**Issue by bigos** [sirherrbatka/cl-data-structures#7]
Exploring algorithms I found the answer

`(cl-data-structures.algorithms:to-list  container )` 

https://sirherrbatka.github.io/cl-data-structures/l_7.html#3377716077867048580

**Comment by sirherrbatka** [comment]
All ranges are traversed the same way: 

https://gist.github.com/sirherrbatka/d2134ae52da368d2216dde8ee668c006

**Comment by bigos** [comment]
Thank you very much for your answers.

**Comment by sirherrbatka** [comment]
Happy to help.
