### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [sirherrbatka/cl-data-structures#8]
Building with SBCL 2.4.6.70-a4f5037f5 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 433de7d0645810119d49903169ba655ef2321ffb

*cl-data-structures-tests* fails to build because of a failure in  _cl-data-structures_.

*cl-data-structures* fails to build with the following error:

```
; caught WARNING:
;   Argument of type (OR REAL VECTOR) cannot be used as a keyword.
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD tid=2175630 "main thread" RUNNING {1000E00003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-data-structures" "sequences" "rrb" "api">

```

[Full log here](http://report.quicklisp.org/2024-07-19/failure-report/cl-data-structures.html)

**Comment by sirherrbatka** [comment]
fixed
